"""initial_schema

Revision ID: 20fac4e950fa
Revises: 
Create Date: 2026-08-10 16:38:32.264466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20fac4e950fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('human_action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_events_source', 'audit_events', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_table('bank_statement_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_file_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statement_imports_status'), 'bank_statement_imports', ['status'], unique=False)
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_account_code'), 'chart_of_accounts', ['account_code'], unique=True)
    op.create_index(op.f('ix_chart_of_accounts_account_type'), 'chart_of_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_chart_of_accounts_is_active'), 'chart_of_accounts', ['is_active'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_at'), 'documents', ['uploaded_at'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('original_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_items_source', 'review_items', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_review_items_review_type'), 'review_items', ['review_type'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_statement_import_id', sa.UUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_statement_import_id'], ['bank_statement_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_amount'), 'bank_transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_statement_import_id'), 'bank_transactions', ['bank_statement_import_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_status'), 'bank_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_table('document_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('subtotal_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_status'), 'document_extractions', ['status'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('extraction_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extraction_id'], ['document_extractions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_document_id'), 'journal_entries', ['document_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_extraction_id'), 'journal_entries', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_amount >= 0', name='chk_credit_amount_non_negative'),
    sa.CheckConstraint('debit_amount >= 0', name='chk_debit_amount_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_entry_id', 'line_number', name='uq_journal_entry_line_number')
    )
    op.create_index(op.f('ix_journal_entry_lines_account_id'), 'journal_entry_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('amount_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('date_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('vendor_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_matches_bank_transaction_id'), 'reconciliation_matches', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_journal_entry_id'), 'reconciliation_matches', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_status'), 'reconciliation_matches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_matches_status'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_journal_entry_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_bank_transaction_id'), table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_account_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_extraction_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_document_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_document_extractions_status'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_statement_import_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_amount'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_review_type'), table_name='review_items')
    op.drop_index('idx_review_items_source', table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_documents_uploaded_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chart_of_accounts_is_active'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_account_type'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_account_code'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    op.drop_index(op.f('ix_bank_statement_imports_status'), table_name='bank_statement_imports')
    op.drop_table('bank_statement_imports')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index('idx_audit_events_source', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
